# Generated by Django 6.0 on 2025-12-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utilisateur",
            old_name="partage_donnees",
            new_name="can_be_contacted",
        ),
        migrations.RenameField(
            model_name="utilisateur",
            old_name="peut_etre_contacte",
            new_name="can_data_be_shared",
        ),
    ]
